### ISSUE TITLE
"Forgetting" commands

### ISSUE THREAD

**Issue by charles-e** [tgrosinger/leader-hotkeys-obsidian#7]
**Describe the bug**
Somehow the plugin forgets many of the available commands that can be triggered. When this happens it will disable existing bindings.  For example, I am using apple-b as the leader.  I was at one point able to bind <leader>-e to "open in default app" but then it would stop working.  When I look at the settings screen it shows the <leader>-e with a blank binding.  
If I turn off then turn on the plugin, it will temporarily restore the available bindings.
(and then it will again forget - I can not determine what triggers this behavior.)

**Desktop (please complete the following information):**
 - OS: MacOS (11.1)
 - Obsidian Version: 22
 - Leader Hotkeys Version: 0.1.1

**Additional context**

**Comment by tgrosinger** [comment]
Oh that is very interesting. I am using undocumented API functionality to learn the list of available commands, so it's possible that the place I am reading from is not always in the state I expect.

Are you able to find a pattern on what you have done before it disappears?

**Comment by charles-e** [comment]
Sorry I am out of ideas. All I know is that it seems to go back to good state after turning it off and back on.

-- stay safe

**Comment by dcrimmin** [comment]
I can confirm this bug as it was originally posted. I mostly use this on MacOS (11.2.3) but I also have the same problems on Win 10. I'm currently using Obsidian 11.9. 

I originally came to this post because when I would try to enter a new leader key the drop down showing the available commands would only give me a partial list of what I knew was available. The list I would get seemed tied to the size of the drop down, which would scroll to start with but then just stop when the drop down reached the bottom of the screen.  At this point it hadn't occurred to me to do the disable/enable trick.  What I had worked and I wasn't losing commands (as described in the original post) but since I only had a few commands I could choose from it was basically broken. Now, after trying the disable/enable trick, I am able to get, what looks to be, the complete list of commands in the drop down. But, after entering a new leader key with one of the commands that I previously couldn't see, I couldn't get anything to respond to the my leader hotkey (cmd + K on Mac/ Alt + K on PC) so then I disable/enable and I realize I'm getting a longer list of commands but not the whole list. Exiting the program and starting again would usually result in the leader key working (on a command from the short list) but then some but not all of the new commands from the longer list would be blank. I mean sort of blank in that if I tried to assign something else to that same key I get a message that key was already in use.  I've tried to narrow it down a bit more but  have given up for now. If you would like me to run a specific scenario, let me know. 

This has the potential to be a super useful plug-in but for now it's just easier to hit cmd+p, type a couple of chars and hit enter. 

Good luck.
